questions = {
    'org_name': {'q': "What is your organization's name?", 'category': 'org_info', 'format': 'text_input', 'short_desc': 'organization name'},
    'org_website': {'q': "What is your organization's website?", 'category': 'org_info', 'format': 'text_input', 'short_desc': 'organization website'},
    'org_mission': {'q': "What is your organization's mission?", 'category': 'org_info', 'format': 'text_area', 'short_desc': 'organization mission'},
    #'org_audience': {'q': "Who is the organization\'s target population?", 'category': 'org_info', 'format': 'text_input', 'short_desc': 'organization target audience'},
    #'org_kpis': {'q': "Please provide any key performance indicators (KPIs) you wish to highlight in this LOI", 'category': 'org_info', 'format': 'text_area', 'short_desc': 'organization kpis'},
    'found_name': {'q': "What is the name of the foundation to whom sending an LOI?", 'category': 'foundation_info', 'format': 'text_input', 'short_desc': 'foundation name'},
    'found_alignment': {'q': "What are the Foundation\'s major funding area(s) for which you see alignment with your grant request?", 'category': 'foundation_info', 'format': 'text_area', 'short_desc': 'project alignment areas with foundation'},
    'found_request': {'q':"How much money are you seeking from this foundation?", 'category': 'foundation_info', 'format': 'text_input', 'short_desc': 'money requesting from foundation'},
    'prog_name': {'q':"What is the name of the project/program you need to fund?", 'category': 'project_info', 'format': 'text_input', 'short_desc': 'program name'},
    'prog_description': {'q':"Please provide a description of this program", 'category': 'project_info', 'format': 'text_area', 'short_desc': 'program description'},
    'prog_budget': {'q':"What is the total budget for the program?", 'category': 'project_info', 'format': 'text_input', 'short_desc': 'program budget'},
    'prog_audience': {'q': "Who is the program\'s target population?", 'category': 'project_info', 'format': 'text_area', 'short_desc': 'program target audience'},
    #'fund_uses': {'q':"How will these funds be used within the scope of the program?", 'category': 'project_info', 'format': 'text_input', 'short_desc': 'program use of funds'},
    'prog_activities': {'q': 'What are the program\'s activities?', 'category': 'project_info', 'format': 'text_area', 'short_desc': 'program activities'},
    'prog_outcomes': {'q':"What are the anticipated outcomes of the program?", 'category': 'project_info', 'format': 'text_area', 'short_desc': 'program outcomes'},
    #'prog_partners': {'q': "Do you have partners in this program?", 'category': 'project_info', 'format': 'text_input', 'short_desc': 'program partners'},
    'prog_timeline': {'q':"Please provide program timeline (e.g., dates, length, etc.)", 'category': 'project_info', 'format': 'text_area', 'short_desc': 'program timeline'},
    'add_info': {'q':"Is there any additional information you want to include in the LOI?", 'category': 'additional_info', 'format': 'text_area', 'short_desc': 'additional info'}
    }